name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v3.6.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
         name: tmp-zip
         path: tmp/*.zip
